spring:
  docker:
    compose:
      lifecycle-management: start_and_stop
      stop:
        command: down

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  sql:
    init:
      mode: always

